### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AlexBrunetti** [DarioFi/OrchestraChess#2]
Ciao,
il mio compilato crasha con "thread 'main' has overflowed its stack", anche su macchina AVX2/BMI, anche con la net in cartella.

Alex

**Comment by DarioFi** [comment]
Buonasera,
potrebbe crashare perchè non trova il file tree.json, che va scaricato usando `dvc pull`. Qual è l'errore preciso? Inoltre cosa dice se viene compilato senza la flag --release?

Dario

**Comment by AlexBrunetti** [comment]
Ciao,
l'errore preciso è quello che ho scritto: "thread 'main' has overflowed its stack";
tree json l'ho scaricato anche con dvc;
l'errore si genera anche con il compilato non release;
gli altri compilati in Rust in genere mi funzionano correttamente.
Potresti eventualmente pubblicare un eseguibile per Windows, possibilmente in una versione plain (senza AVX/AVX2/BMI)?

Grazie,
Alex

**Comment by DarioFi** [comment]
Ciao,
ho provato da una VM con windows e ho lo stesso errore, purtroppo avevamo testato solo su MacOs e Linux. Il problema è oscuro in quanto non dà nessuna backtrace. Come fix temporaneo se vuoi provarlo puoi runnarlo su WSL, lì dovrebbe funzionare (spero). Non usiamo nessuna intrinsic SIMD (tranne quelle automatiche scritte dal compilatore se passi '-C target-cpu=native' a cargo) quindi non credo l'errore venga da lì. 
Spero possa essere d'aiuto.
Dario

**Comment by mattia-scardecchia** [comment]
Ciao,
Forse il problema è simile a questo (nel nostro magic.rs): https://www.reddit.com/r/rust/s/yjIUXD4pZV
Indagheremo e ti faremo sapere asap.
Mattia

**Comment by AlexBrunetti** [comment]
Ho trovato anche questo (linkato nel tuo link) https://users.rust-lang.org/t/what-can-i-do-to-avoid-thread-main-has-overflowed-its-stack-when-working-with-large-arrays/77091 e ho provato a giochicchiare un po', supportato anche da ChatGPT ma non ho risolto un bel niente. Tra parentesi, non conosco un bit di Rust :)
Attendo eventuali vostre.
Grazie,
Alex

**Comment by mattia-scardecchia** [comment]
Ciao,
come pensavo il problema era dovuto al fatto che il linker alloca significativamente meno spazio per lo stack su windows rispetto a macOS e Linux su cui avevamo testato il bot. Ho appena pushato un commit che, almeno sulla mia VM, sembra risolvere il problema. Facci sapere se ora fila liscio!
Mattia

**Comment by AlexBrunetti** [comment]
Ciao,
ci siamo quasi! Intanto segnalo dei warning ininfluenti in fase di compilazione:
```
warning: unused import: `std::fmt::format`
 --> src\tests\benchmark.rs:1:5
  |
1 | use std::fmt::format;
  |     ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::process::exit`
 --> src\tests\benchmark.rs:2:5
  |
2 | use std::process::exit;
  |     ^^^^^^^^^^^^^^^^^^

warning: unused import: `std::process::exit`
  --> src\main.rs:18:5
   |
18 | use std::process::exit;
   |     ^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::tests::benchmark::test_n_nodes`
  --> src\main.rs:19:5
   |
19 | use crate::tests::benchmark::test_n_nodes;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: `rust-chess-bot` (bin "rust-chess-bot") generated 4 warnings (run `cargo fix --bin "rust-chess-bot"` to apply 4
 suggestions)
    Finished release [optimized] target(s) in 19.34s
```
che ho eliminato togliendo le due coppie di use indicate. All'esecuzione invece il tutto panica, perché non trova il libro:
```
H:\msys64\home\Alex\OrchestraChess>target\release\rust-chess-bot.exe
thread 'main' panicked at src\book.rs:20:49:
Unable to open file: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." } [eccetera]
```
e questo perché dvc pull non pulla, con una serie di errori assurdi, e quindi non c'è il tree,json. In ogni caso il libro non serve (a me e agli altri "tester") e quindi l'ho disattivato in book.rs. Ma questo non stoppa l'esecuzione di OpeningBook!

Domanda: non c'è un modo meno complicato di gestire lo scarico del libro, e dell'opzione libro sì/libro no?

Grazie,
Alex

**Comment by DarioFi** [comment]
Ciao,

non so bene perchè dvc non funziona, comunque ora disattivare il book cambiando la constante `USE_BOOK` fa si che il programma non provi a leggerlo, quindi dovrebbe andare. Usiamo dvc poichè il file è troppo pesante per git (214M).

Facci sapere se funziona!

Dario

**Comment by AlexBrunetti** [comment]
No amico, non funziona, te l'ho scritto. Tu fai il check di USE_BOOK dentro OpeningBook::query, mentre OpeningBook::new gira comunque e lì si rompe. Viene chiamata da new_eninge() con "book: OpeningBook::new(BOOK_FILE)", sembra tipo un attributo dell'oggetto Engine, ma non sapendo niente di rust non so come rimuoverla o assegnarci qualcosa di nullo, dovrei fare 100 tentativi.
Per quanto riguarda la modalità di download del libro sarebbe più semplice dire: il book è qui, e il link :)
Hai un libro molto più piccolo di test intanto, o puoi indicarmi la sua struttura?

Grazie,
Alex

**Comment by DarioFi** [comment]
Hai pullato l'ultimo commit? ora dentro new c'è un branch che controlla use_book.

Dario

**Comment by DarioFi** [comment]
Comunque se vuoi un book vuoto:
 {
  "Mov": "a1a1",
  "Score": 0,
  "Children": []
}
ma non dovrebbe essere necessario

**Comment by AlexBrunetti** [comment]
Ci siamo! Sia con book=false che con il book vuoto funziona!
Se può esservi utile ho messo l'exe in un fork, Ho dato un nome alla release (data e sigla del compilatore), cosa che suggerisco di fare sempre. Vi faccio sapere nei prossimi giorni qual è la forza Elo del vostro programma.

Grazie,
Alex
